name: On Tag
on:
  push:
    tags:
      - "*.*.*"
env:
  SUPPLY_UPLOAD_MAX_RETRIES: 5
jobs:
  app_build:
    name: Github release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - uses: ./.github/actions/create-release-number
        name: Create Release Number
        id: rel_number
      - uses: ./.github/actions/create-release-notes
        name: Create Release Notes
        with:
          tag-name: ${{ steps.rel_number.outputs.version }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/inflate-secrets
        name: Inflate Secrets
        with:
          keystore: ${{ secrets.ORIGINAL_KEYSTORE_FILE }}
      - uses: gradle/wrapper-validation-action@v2
        name: Validate Gradle Wrapper
      - name: Build Release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.ORIGINAL_KEYSTORE_FILE_PASSWORD }}
          KEYSTORE_ALIAS: ${{ secrets.ORIGINAL_KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.ORIGINAL_KEYSTORE_FILE_PASSWORD }}
          VERSION_CODE: ${{ steps.rel_number.outputs.version-code }}
        run: |
          ./gradlew -Pversion=${{steps.rel_number.outputs.version}} :app:assembleRelease
      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          path: ./**/*.apk
      - name: Create Github Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ steps.rel_number.outputs.version }}
          body_path: ./app/build/outputs/changelogGithub
          draft: false
          files: |
            ./app/build/outputs/apk/release/app-release.apk
